# Sample request that should work
POST http://localhost:8080/sendCustomDTO
Content-Type: application/json
{  
    "address": "68469 Weinheim, Obere Straße 5b",
    "city": "Mannheim",
    "nintendo": "The Legend of Zelda"
}

# Sample request that should not work
POST http://localhost:8080/sendCustomDTO
Content-Type: application/json
{  
    "address": "68469 Weinheim, Obere Straße 5b",
    "city": "1212",
    "nintendo": "The of 12"
}